[config]
# Scheduled states control
# schedule_enabled: enable reading and triggering states from schedule.
# scheduled_source: source json to read target states from.
schedule_enabled = true
schedule_source = "./data/schedule.json"

# Web Server control
# web_enabled: enable web server to trigger state changes on demand.
# web_host: ip address to listen on.
# web_port: port to listen on.
web_enabled = true
web_host = "0.0.0.0"
web_port = 8080

# Application log output
# write_logs: enable writing to a log file.
# write_logs_file: file to write logs to if enabled.
write_logs = false
write_logs_file = "./data/hypnos.log"
# NOTE:
#   Logging level can be changed via `.env` or system environment variable 'HYPNOS_LOG_LEVEL'. (warn, info, debug)
